### ISSUE TITLE
Invalid res_tr_path.

### ISSUE THREAD

**Issue by Xxcarbon22xX** [abnerfs/round_end_sounds#1]
Hello, im using SourceMod 1.7.3-dev+5258 and i have an issue with this plugin. I was trying to add CT and TT sounds to other folders like: misc/ServerRsCT , misc/ServerRsTT or misc/ServerRs/CT, misc/ServerRs/TT. Doesn't work.

In my console i only see this:
[AbNeR RES] INVALID TR SOUND PATH.
[AbNeR RES] CT_SOUNDS: 30 sounds 

Please, if you can do something with that it will be nice. This plugin is very useful and i can't imagine my server without it :(

**Comment by abnerfs** [comment]
Hi bro, check if u are using the latest version of the plugin: https://github.com/abnerfs/round_end_sounds/releases

it seems that the CT sounds were loaded, they are playing when ct wins?

**Comment by Xxcarbon22xX** [comment]
I'm using the latest version of the plugin. I updated it yesterday, deleted all old files. Today i noticed that it's loading all sounds, but the message in console is incorrect. 

It plays TT and CT sounds correctly, maybe the messages are wrong only?

**Comment by abnerfs** [comment]
i was having some problems with play_to_the_end so i solve simplify the plugin, but i'm planning make an stable version with play_to_the_end feature, i can improve "res_print_to_chat_mp3_name" too, but i'm really busy now, be patient :smile:
