### ISSUE TITLE
Server crashes when plugin is enabled

### ISSUE THREAD

**Issue by sandy-bridge** [abnerfs/round_end_sounds#10]
Hi, I have a problem running this server on my CSGO server. The server crashes as the clients connect to the server if the plugin is enabled. I used the latest versions of MM:S and SM, and this plugin itself. I had no other plugins running. The server runs on Linux.

Is this a known issue?

**Comment by ichiballs** [comment]
Happens to me aswell, but wasn't happening before i added new clips, i think it might be the properties of the new files i added.

**Comment by abnerfs** [comment]
send me the songs that you added, i will test

**Comment by abnerfs** [comment]
Do you have any log?

**Comment by ichiballs** [comment]
i went through logs and there is not much really, all that happens is server encounters a seg fault when map is initializing out of nowhere.

**Comment by Armadillomeister** [comment]
Yes I have the same problem when it says "world/map initializing" and "downloading blabla files.mp3" it wont continue loading onto the server. please help!

**Comment by Armadillomeister** [comment]
Found the problem guys!
Type **sv_cheats 1** in your console while on your csgo start-page/main menu/Lobby.
Then **sv_allowupload 1** and **sv_allowdownload 1**.
Now connect to your Dedicated Server.
All mp3 or other files should be loaded now and you will join the match. (team selection)
The only problem now left is that the songs dont play even though everything is loaded correctly. That should be a problem of the plugin or the client volume so @abnerfs will have to look after that.
![Counter-strike  Global Offensive Screenshot 2021 06 30 - 18 06 41 14 (2)](https://user-images.githubusercontent.com/86675543/123995013-2f00bd00-d9ce-11eb-9eec-de9ba100953b.png)
