### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by Theelmodog** [abnerfs/round_end_sounds#14]
Hey!

After start it tells in the console the following:
[AbNeR RES] SOUNDS: 0 sounds loaded from "sound/misc/tecnohard"
[AbNeR RES] DRAW SOUNDS: 0 sounds loaded from "sound/misc/tecnohard"
But I have .mp3 files in sound/misc/tecnohard. What could be the issue?

**Comment by abnerfs** [comment]
Check folder permissions if you are using ftp

**Comment by Theelmodog** [comment]
The server is on my pc. It's a test server, because I'm new to cs server making.

**Comment by abnerfs** [comment]
Send me a picture of your sound/misc/tecnohard folder

**Comment by Theelmodog** [comment]
![Képkivágás](https://user-images.githubusercontent.com/12050120/69485527-19660180-0e41-11ea-8c62-965ebac1cc95.PNG)

**Comment by abnerfs** [comment]
are apfel and banane  **.mp3** files?

**Comment by Theelmodog** [comment]
yes

**Comment by abnerfs** [comment]
Enable file name extensions and send me another picture 
![image](https://user-images.githubusercontent.com/14078661/69485666-72be3880-0e21-11ea-9933-538319e58de9.png)

**Comment by Theelmodog** [comment]
![Képkivágás](https://user-images.githubusercontent.com/12050120/69485686-300d5800-0e43-11ea-92aa-a5fd38bbae71.PNG)

**Comment by abnerfs** [comment]
The musics are in the wrong folder, they are in **sound/music/misc/tecnohard**, they should be in **sound/misc/tecnohard**
