### ISSUE TITLE
INVALID TR SOUND PATH.

### ISSUE THREAD

**Issue by szogi1910** [abnerfs/round_end_sounds#3]
Hello, im using SourceMod 1.8 - build 5937 and i have an issue with this plugin. I was trying to add CT and TT sounds to other folders

[AbNeR RES] INVALID TR SOUND PATH.
[AbNeR RES] CT_SOUNDS: 88 sounds loaded.
[AbNeR RES] SOUNDS: 88 sounds loaded.

**Comment by abnerfs** [comment]
Can you send me some sounds that you are using?

**Comment by szogi1910** [comment]
Sorry that so long but I had limited time.
Examples of sounds: http://www103.zippyshare.com/v/VnSTkKDd/file.html

// Path off tt sounds in /cstrike/sound
// -
// Default: "roundsound/"
res_tr_path "roundsound/wrzesien"
