### ISSUE TITLE
missing feature: mapend_sound

### ISSUE THREAD

**Issue by ElCurioso** [abnerfs/round_end_sounds#4]
First: awesome plugin! But one feature would still make it more awesone:

res_mapend_path "misc/tecnohard/mapendsound" - Path of sounds played after last round.

requested because: 
Roundend-sounds are "normaly" short in duration. With the cvar "mp_chattime" you can give a sound -(ONLY BEFORE MAPCHANGE)- the time it needs to be played. A Server admin could e.g. "Cut" his long-duration-map-end-sounds to XXsec. and set mp_chattime to "XX". Voilà.

**Comment by abnerfs** [comment]
I think it´s better do this feature in a new plugin, wait for my future map end sounds plugin
