### ISSUE TITLE
Bug plugin ver. 3.6

### ISSUE THREAD

**Issue by Majkovsky** [abnerfs/round_end_sounds#7]
I think there is some kind of bug in latest version. When you change the volume and you die you will hear the sound "from the dead body" - when you switch to another player you wil get effect like the farther you are the quieter sound is. Maybe that's because of the emitsoundany or game "bug" with latest sound positioning changes. I haven't tested it with EmitSound instead of EmitSoundAny. 

// By author Spyrek

**Comment by abnerfs** [comment]
Try new version 3.6.2 https://github.com/abnerfs/round_end_sounds/releases
