### ISSUE TITLE
Required extension "Client Preferences" file("clientprefs.ext") not running

### ISSUE THREAD

**Issue by GepmesterHUN** [abnerfs/round_end_sounds#8]
abner_res.smx ([CS:GO/CSS] AbNeR Round End Sounds): Required extension "Client Preferences" file("clientprefs.ext") not running
clientprefs.smx (Client Preferences): Required extension "Client Preferences" file("clientprefs.ext") not running
 etc...

What to do? I cant find the solution on Google 😢

**Comment by abnerfs** [comment]
Client Preferences is a sourcemod native extension, try update your sourcemod to a new version
