### ISSUE TITLE
[Feature Request] Update plugin functions

### ISSUE THREAD

**Issue by crashzk** [abnerfs/round_end_sounds#9]
Some suggestions for future plugin updates:

**_- Update CVAR res_draw_path to read both scripts in case the user wants;_**
Currently you can only choose 0 - Don't play sounds, 1 - Play TR sounds, 2 - Play CT sounds

**_- Check CVAR res_client_preferences;_**
Whenever I give retry on the server I have to select the volume setting of the sound, and if I deactivate the sounds whenever the retry also returns it to turn on the sounds. (I did not research right about it, apparently it happened once with me)

**_- Update CVAR res_refresh;_**
It would be interesting if the plugin will refresh automatically whenever it new music, whenever it detects updates in the music config, i do not know if that's possible.

I would also have a question, the audio I edit has to be at most 128Kbps, which would be the most recommended? It would be nice to also put on the official topic for others already know what would be recommended...

**Comment by abnerfs** [comment]
I'll work on that this weekend (I hope)

**Comment by paulocrash** [comment]
Just passing by to remember not to forget these suggestions on... :)

**Comment by abnerfs** [comment]
Since this is open for over 3 years now and I don't think I will have time to prioritize it anytime soon I'm closing this for now
